bchinfo/bch.info

app/wallets.html

Does not detect received funds.

Remove Neutrino wallet

---

app/nodes.html

Fix Flowee the Hub name

---

app/wallets.html

both mobile and desktop versions

Add links for Melis Wallet

---

app/templates/base.njk
app/tools/cashaddr.html
js/scripts.js

- Remove inline JavaScript
- Load JavaScript at the end of the body
- Add comments

Refactor cashAddr conversion

---

app/templates/footer.njk
app/tools/broadcast.html
app/tools/index.html
js/scripts.js
lang/en/broadcast.yaml
lang/en/footer.yaml
lang/en/tools.yaml

Note that this relies only on rest.bitcoin.com at this point. It would be good to have an least one other endpoint for redundancy in case one goes down.

Add broadcast transaction tool

---

app/wallets.html

Add Electron Cash mobile wallet

---

app/data/chips.json

Add CHIP-2021-03-12 Multiple OP_RETURNs for Bitcoin Cash

---

app/upgrade.html

This supercedes #147 which has a conflict in the same line.

Knuth is may 2022 ready

---

app/nodes.html

Flowee currently does not have a version that follows the May 2022 upgrade.

Notice on Flowee post May upgrade

---

app/wallets.html

Maintainer took down link to wallet.

Remove pokket from list of wallets

---

app/data/exchanges.json

Add Bitvavo (Dutch exchange) to the list.

Add Bitvavo to the list of exchanges

---

app/wallets.html

Added KeepKey under hardware wallet since it has bch support. Addresses issue #61.

Added KeepKey to list of hardware wallets. Update wallets.html.

---

app/data/chips.json

Excessive Block-size Adjustment Algorithm (EBAA) for Bitcoin Cash

Add EBAA CHIP

---

app/community.html
app/templates/footer.njk
lang/de/community.yaml
lang/de/footer.yaml
lang/en/community.yaml
lang/en/footer.yaml
lang/es/community.yaml
lang/es/footer.yaml
lang/fr/community.yaml
lang/fr/footer.yaml
lang/it/community.yaml
lang/it/footer.yaml
lang/ja/community.yaml
lang/ja/footer.yaml
lang/pl/community.yaml
lang/pl/footer.yaml
lang/pt/community.yaml
lang/pt/footer.yaml
lang/ru/community.yaml
lang/ru/footer.yaml
lang/th/community.yaml
lang/th/footer.yaml
lang/zh/community.yaml
lang/zh/footer.yaml

Add a simple "community links" page which is a loose collection of gathering places and pages.

Add community links page on footer

---

app/templates/base.njk

Hide 2023 upgrade banner

---

app/explorers.html

Prune old ones that has not kept up or not in service, added new ones

Update explorers list

---

app/wallets.html
lang/de/wallets.yaml
lang/en/wallets.yaml
lang/es/wallets.yaml
lang/fr/wallets.yaml
lang/it/wallets.yaml
lang/ja/wallets.yaml
lang/pl/wallets.yaml
lang/pt/wallets.yaml
lang/ru/wallets.yaml
lang/th/wallets.yaml
lang/zh/wallets.yaml

Cashonize doesn't fit into any of our previous categories so it needs its own section.  More translations can wait.

Add a browser wallet section 

---

app/wallets.html

Zapit is a non-custodial wallet. (Live on Android and iOS)
[Website](https://zapit.io)  |  [Android](https://play.google.com/store/apps/details?id=io.wallet.zapit&pcampaignid=pcampaignidMKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1&pli=1) | [iOS](https://apps.apple.com/in/app/zapit-io/id1558433083)

Add Zapit Wallet to the list of mobile wallets

---

app/upgrade.html

https://twitter.com/KnuthNode/status/1754462895843193261

add knuth to upgraded releases

---

app/data/chips.json

It's been more than a month since activation!

change EBAA to activated

---

app/wallets.html

Solves https://github.com/bchinfo/bch.info/issues/237

Add Cake Wallet
